### ISSUE TITLE
Fragment Cityポップ作成

### ISSUE THREAD

**Issue by marutakan** [Fake-Chord-Union/fragment-city#2]
おコンさんタスク
- デザインはジャケットベース
- 値段も表示
### 利用テンプレート

http://works.o3asterisk.com/cdpop/

**Comment by kitsunenosekai** [comment]
やってる

**Comment by kitsunenosekai** [comment]
すっごい雑にやってる

**Comment by kitsunenosekai** [comment]
おにくたべたい

**Comment by kitsunenosekai** [comment]
ふざけverできた

**Comment by kitsunenosekai** [comment]
わざとハミ出させて目立たせた感じです。
ふざけないverでは余計な文言が消えてタイトルと価格のみの表示になります。

どっちにしろ切るのめんどくさい仕様ですがピザカッター駆使してがんばってください！！！！

**Comment by kitsunenosekai** [comment]
両方できた

**Comment by kitsunenosekai** [comment]
おにくたべたいよお

**Comment by yashima8to7** [comment]
みました
今日の夜に八嶋の手で印刷＋裁断やるです

**Comment by yashima8to7** [comment]
印刷・裁断しました

**Comment by marutakan** [comment]
リリース済みなのでクローズ
