### ISSUE TITLE
ポスター作成

### ISSUE THREAD

**Issue by marutakan** [Fake-Chord-Union/fragment-city#3]
ワイヤーフレーム
https://fakechordunion.slack.com/files/maru/F12V0DCM9/untitled.png
![image](https://cloud.githubusercontent.com/assets/4906046/14750358/5ff5e73c-08ff-11e6-9316-49f2794a0754.png)

**Comment by yashima8to7** [comment]
594x210(A4を2枚並べたサイズ)で作成中です。
・全体のバランスは良いか。
・ブース番号のフォントはこんな感じで良いか。今は小塚ゴシック。ロゴのフォントへ似せてる。
・ブース番号のフォント太さで悩んでいる。全体のバランスは"m32016spring"、遠くから見たときなら"m32016spring_2"が良さそう。個人的には後者。
"m32016spring"
![fcu_poster_m32016spring](https://cloud.githubusercontent.com/assets/5805514/14750387/894c6980-08ff-11e6-989e-820971d38928.png)
"m32016spring_2"
![fcu_poster_m32016spring_2](https://cloud.githubusercontent.com/assets/5805514/14750388/8988b494-08ff-11e6-8e6c-85d5680ad14b.png)

**Comment by yashima8to7** [comment]
とりあえず明日どっちも印刷してみる。良さそうな方で決めます。

**Comment by marutakan** [comment]
@yashima8to7 ブース名、改行じゃなく半角スペースでもいいかも。
`第一展示場 G-20a`って感じで

**Comment by marutakan** [comment]
フォントは後者がよさそう

**Comment by yashima8to7** [comment]
上記はんえいするっす。

**Comment by yashima8to7** [comment]
修正
![fcu_poster_m32016spring_3](https://cloud.githubusercontent.com/assets/5805514/14751344/5a520ab8-0904-11e6-82ef-2ed461f29fae.png)

**Comment by marutakan** [comment]
:+1: :shipit:

**Comment by yashima8to7** [comment]
そしたらこれで

**Comment by yashima8to7** [comment]
close

**Comment by marutakan** [comment]
印刷してダメそうなら再オープンで
