### ISSUE TITLE
頒布物一覧作成

### ISSUE THREAD

**Issue by marutakan** [Fake-Chord-Union/fragment-city#4]
ワイヤーフレーム
https://fakechordunion.slack.com/files/maru/F12TN65GU/wireframe.png
![image](https://cloud.githubusercontent.com/assets/4906046/14750403/9f5571fe-08ff-11e6-99fd-543312d74f5f.png)
- 一番外側の枠線は都合上囲んだだけなので注意
- 実際はA3縦想定なので、配置のバランスはお手数だけどよしなにお願いしたい
- ワイヤーにはないが(すまぬ)、新譜旧譜の表示もあるとよさげ

**Comment by yashima8to7** [comment]
あークソ旧譜の画像データがない。フォルダ漁る。

**Comment by marutakan** [comment]
Dropboxにないかしら

**Comment by yashima8to7** [comment]
そのはずなので探してる。

**Comment by marutakan** [comment]
`FakeChordUnion/2015M3春` BTHLC、EDEN、Mortal Edenはこの中かな
DiffusionはSlackのchにあるはず

**Comment by yashima8to7** [comment]
あったｔｈｘ
やや頭回ってないのでいいところで切り上げます

**Comment by yashima8to7** [comment]
jpeg形式だけれどひとまずデモ。
配置、文字組み、文面はとりあえず入れてる。

**Comment by yashima8to7** [comment]
大まかなジャンルくらいは併記するべきかなーと思ったので、ワイヤーとずれちゃうけれど追記した。

**Comment by yashima8to7** [comment]
↑は仮なので、寝て起きたら修正します。

**Comment by marutakan** [comment]
:pray: :bow:
あとはA3に合わせて位置調整してしまえば良さげ

**Comment by yashima8to7** [comment]
できたので印刷します

**Comment by marutakan** [comment]
リリース済みなのでクローズ
